server:
  port: 8085

eureka:
  instance:
    hostname: registry-service
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:23310/smc_stock_price
    username: root
    password: just4mysql