server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:23307/smc_stock_exchange
    username: root
    password: just4mysql