server:
  port: 8083

eureka:
  instance:
    hostname: company-service
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://docker_smc_company:3306/smc_company
    username: root
    password: just4mysql